version: "3"

networks:
  openmetric_quickstart:
    driver: bridge

services:
  carbon:
    image: openmetric/go-carbon
    volumes:
      - ./conf:/openmetric/conf
    networks:
      - openmetric_quickstart
  relay:
    image: openmetric/carbon-c-relay
    volumes:
      - ./conf:/openmetric/conf
    networks:
      - openmetric_quickstart
    ports:
      - "2003:2003"
    depends_on:
      # relay relies on 'carbon' to be resolved
      - carbon
  zipper:
    image: openmetric/carbonzipper
    volumes:
      - ./conf:/openmetric/conf
    networks:
      - openmetric_quickstart
    depends_on:
      - relay
  api:
    image: openmetric/carbonapi
    volumes:
      - ./conf:/openmetric/conf
    networks:
      - openmetric_quickstart
    ports:
      - "5000:5000"
    depends_on:
      - relay
  grafana:
    image: openmetric/grafana
    volumes:
      - ./conf:/openmetric/conf
    networks:
      - openmetric_quickstart
    ports:
      - "3000:3000"
    depends_on:
      - relay
